Lipay/HW-9
tms-net/net-10 pull request #67
Opened 2023-05-09 19:01 UTC by EvgenyLipayMinsk

2023-05-19 18:21 UTC, diman84 reviewed
Обратите внимание, что работа с консолью должна осуществляться вне классов, реализующих бизнес логику

2023-05-19 18:21 UTC, diman84 commented on homeworks/homework-09/results/lipay/ATM/ATMClient.cs
> +                Console.WriteLine("Not enough money on card");
ATMClient может использоваться не только в консольных приложениях, ошибка должна быть обработана вне класса

2023-05-19 18:21 UTC, diman84 commented on homeworks/homework-09/results/lipay/ATM/ATMClient.cs
> +            return _accountBalance.Value;
Обработайте случай вызова метода, когда баланс не указан (карточка не вставлена)

2023-05-20 08:55 UTC, EvgenyLipayMinsk commented on homeworks/homework-09/results/lipay/ATM/ATMClient.cs
> +            return _accountBalance.Value;
Исправил. Подумал пусть возвращает null
![image](https://github.com/tms-net/net-10/assets/69685960/5e55a2bc-6273-46e3-b8bc-a99904e9e62f)

2023-05-20 09:31 UTC, EvgenyLipayMinsk commented on homeworks/homework-09/results/lipay/ATM/ATMClient.cs
> +                Console.WriteLine("Not enough money on card");
Исправил
![image](https://github.com/tms-net/net-10/assets/69685960/bb9f26af-ef68-45dc-8276-4278bba7b984)

2023-05-27 15:05 UTC, diman84 commented on homeworks/homework-09/results/lipay/ATM/ATMClient.cs
> +        public string _cardStatus;
Публичные поля - это плохо, попробуйте использовать Свойства

2023-05-27 15:07 UTC, diman84 commented on homeworks/homework-09/results/lipay/ATM/ATMClient.cs
> +            Failed
Больше подходить `Undefined` или что-то вроде того

2023-05-27 15:08 UTC, diman84 commented on homeworks/homework-09/results/lipay/ATM/ATMClient.cs
> +                _cardStatus = "Not enough money on card";
Статус, выраженный в сообщении скорее относится к UI, т.е. тут достаточно значения перечисления

2023-05-27 15:11 UTC, diman84 requested changes
Исправьте замечания в комментариях

2023-05-27 15:11 UTC, diman84 commented on homeworks/homework-09/results/lipay/ATM/ATMClient.cs
> +            // TODO: Реализовать пополнение баланса
На этом этапе карточка тоже может быть не вставлена

2023-05-28 10:46 UTC, EvgenyLipayMinsk commented on homeworks/homework-09/results/lipay/ATM/ATMClient.cs
> +        public string _cardStatus;
Исправил
![image](https://github.com/tms-net/net-10/assets/69685960/1a20ce45-18c0-41a1-a6d5-976bc4796b3d)

2023-05-28 10:50 UTC, EvgenyLipayMinsk commented on homeworks/homework-09/results/lipay/ATM/ATMClient.cs
> +                _cardStatus = "Not enough money on card";
Согласен, исправил и добавил это сообщение в UI
![image](https://github.com/tms-net/net-10/assets/69685960/6c16a402-0aae-4e02-a586-031115dbc465)

2023-05-28 10:51 UTC, EvgenyLipayMinsk commented on homeworks/homework-09/results/lipay/ATM/ATMClient.cs
> +            Failed
Исправил
![image](https://github.com/tms-net/net-10/assets/69685960/a9c4e979-6e7c-4808-8df9-938092f91c18)

2023-05-28 10:59 UTC, EvgenyLipayMinsk commented on homeworks/homework-09/results/lipay/ATM/ATMClient.cs
> +            // TODO: Реализовать пополнение баланса
Исправил. Подумал, что если баланс карточки = null, то значит она не вставлена, поэтому просто присвоил ей null (ничего не изменил). 
![image](https://github.com/tms-net/net-10/assets/69685960/a1f2d2c8-77ea-4891-b869-2e82cd3b4e6e)

2023-05-28 14:56 UTC, diman84 commented on homeworks/homework-09/results/lipay/ATM/ATMClient.cs
> +            Failed
Я имел ввиду `Undefined` вместо `Failed` :)

2023-05-28 15:01 UTC, diman84 commented on homeworks/homework-09/results/lipay/ATM/ATMClient.cs
> +            // TODO: Реализовать пополнение баланса
тут достаточно проверки на `null` для пополнения, без присвоения, но тут есть нюанс: при осуществлении операции, компонент, который будет вызывать метод `TopUp` не сможет получить информацию о том, что она не прошла, и что надо вставить карточку, попробуйте это исправить

2023-05-28 15:02 UTC, diman84 reviewed
Немного изменений еще нужно, замечания в комментариях

2023-05-29 08:42 UTC, EvgenyLipayMinsk commented on homeworks/homework-09/results/lipay/ATM/ATMClient.cs
> +            Failed
Исправил)
![image](https://github.com/tms-net/net-10/assets/69685960/801cdd17-6bdb-4adf-9eec-bcd309968b96)

2023-05-29 10:14 UTC, EvgenyLipayMinsk commented on homeworks/homework-09/results/lipay/ATM/ATMClient.cs
> +            // TODO: Реализовать пополнение баланса
Исправил. Подумал, что тут такая же ситуация как с командой "Снять средства из банкомата". Поэтому можно воспользоваться cardStatus. 
![image](https://github.com/tms-net/net-10/assets/69685960/020fdc53-3749-42da-9425-1da3374035f5)

2023-06-12 17:10 UTC, merged